FROM php:7.4-rc-fpm-alpine as base

MAINTAINER Igor Agapie <igoragapie@gmail.com>

ADD https://raw.githubusercontent.com/iagapie/docker/master/php/script/install-php-extensions /usr/local/bin/

RUN set -ex \
	&& chmod uga+x /usr/local/bin/install-php-extensions \
	&& sync \
	&& apk add --no-cache --virtual .persistent-deps \
		nano \
		unzip \
		zip \
		git \
		shadow \
	&& install-php-extensions \
		gd \
		zip \
		imap \
		ldap \
		pdo_odbc \
		odbc \
		ffi \
		bcmath \
		opcache \
		snmp \
		intl \
		soap \
		xsl \
		bz2 \
		calendar \
		dba \
		enchant \
		exif \
		gettext \
		gmp \
		mysqli \
		pcntl \
		pdo_mysql \
		pdo_pgsql \
		pgsql \
		sockets \
		xmlrpc \
		apcu \
		xdebug

# Xdebug Config

ENV PHP_XDEBUG_REMOTE_HOST=localhost \
	PHP_XDEBUG_REMOTE_PORT=9000 \
	PHP_XDEBUG_IDEKEY=IDEKEY

RUN set -ex \
	&& echo 'xdebug.remote_autostart=1' >> /usr/local/etc/php/conf.d/custom-xdebug.ini \
	&& echo 'xdebug.remote_enable=1' >> /usr/local/etc/php/conf.d/custom-xdebug.ini \
	&& echo 'xdebug.remote_handler=dbgp' >> /usr/local/etc/php/conf.d/custom-xdebug.ini \
	&& echo 'xdebug.profiler_enable=0' >> /usr/local/etc/php/conf.d/custom-xdebug.ini \
	&& echo 'xdebug.profiler_output_dir="/var/www/html"' >> /usr/local/etc/php/conf.d/custom-xdebug.ini \
	&& echo 'xdebug.remote_connect_back=1' >> /usr/local/etc/php/conf.d/custom-xdebug.ini \
	&& echo 'xdebug.remote_host=${PHP_XDEBUG_REMOTE_HOST}' >> /usr/local/etc/php/conf.d/custom-xdebug.ini \
	&& echo 'xdebug.remote_port=${PHP_XDEBUG_REMOTE_PORT}' >> /usr/local/etc/php/conf.d/custom-xdebug.ini \
	&& echo 'xdebug.idekey=${PHP_XDEBUG_IDEKEY}' >> /usr/local/etc/php/conf.d/custom-xdebug.ini

# Install Supercronic

ENV SUPERCRONIC_URL=https://github.com/aptible/supercronic/releases/download/v0.1.8/supercronic-linux-amd64 \
    SUPERCRONIC=supercronic-linux-amd64 \
    SUPERCRONIC_SHA1SUM=be43e64c45acd6ec4fce5831e03759c89676a0ea

RUN set -ex \
	&& curl -fsSLO "$SUPERCRONIC_URL" \
	&& echo "${SUPERCRONIC_SHA1SUM}  ${SUPERCRONIC}" | sha1sum -c - \
	&& chmod +x "$SUPERCRONIC" \
	&& mv "$SUPERCRONIC" "/usr/local/bin/${SUPERCRONIC}" \
	&& ln -s "/usr/local/bin/${SUPERCRONIC}" /usr/local/bin/supercronic

# Install Composer

RUN set -ex \
	&& curl -sS https://getcomposer.org/installer | php -- --install-dir=/usr/local/bin/ --filename=composer

USER www-data

RUN set -ex \
	&& mkdir -p /home/www-data/.composer \
	&& composer g require \
		hirak/prestissimo \
		psy/psysh:@stable \
	&& rm -rf /home/www-data/.composer/cache/*

ENV PATH="/home/www-data/.composer/vendor/bin:${PATH}"

USER root
