FROM php:7.3-cli-alpine as base

MAINTAINER Igor Agapie <igoragapie@gmail.com>

ADD https://raw.githubusercontent.com/iagapie/docker/master/php/script/install-php-extensions /usr/local/bin/

RUN set -ex \
	&& chmod uga+x /usr/local/bin/install-php-extensions \
	&& sync \
	&& apk add --no-cache --virtual .persistent-deps \
		nano \
		unzip \
		zip \
		git \
		shadow \
	&& install-php-extensions \
		gd \
		zip \
		imap \
		ldap \
		pdo_odbc \
		odbc \
		bcmath \
		opcache \
		snmp \
		intl \
		soap \
		xsl \
		bz2 \
		calendar \
		dba \
		enchant \
		exif \
		gettext \
		gmp \
		mysqli \
		pcntl \
		pdo_mysql \
		pdo_pgsql \
		pgsql \
		sockets \
		xmlrpc \
		wddx \
		oauth \
		memcached \
		redis \
		mcrypt \
		apcu \
		xdebug

# Install Composer

RUN set -ex \
	&& curl -sS https://getcomposer.org/installer | php -- --install-dir=/usr/local/bin/ --filename=composer

USER www-data

RUN set -ex \
	&& mkdir -p /home/www-data/.composer \
	&& composer g require \
		hirak/prestissimo \
		psy/psysh:@stable \
	&& rm -rf /home/www-data/.composer/cache/*

ENV PATH="/home/www-data/.composer/vendor/bin:${PATH}"

USER root
