FROM php:7.3-cli-alpine as base

MAINTAINER Igor Agapie <igoragapie@gmail.com>

RUN set -ex \
	&& apk add --no-cache --virtual .persistent-deps \
		nano \
		unzip \
		zip \
		git \
		shadow

RUN set -xe \
	&& apk add --no-cache --virtual .build-deps \
		$PHPIZE_DEPS \
		freetype-dev \
		libjpeg-turbo-dev \
		libpng-dev \
		icu-dev \
		libmcrypt-dev \
		libxml2-dev \
		libxslt-dev \
		pcre-dev \
		libmemcached-dev \
		unixodbc-dev \
		libssh2-dev \
		enchant-dev \
		gmp-dev \
		imap-dev \
		postgresql-dev \
		net-snmp-dev \
		openldap-dev \
		krb5-dev \
		bzip2-dev \
		zlib-dev \
		libzip-dev \
	&& docker-php-source extract \
	&& { \
        echo '# https://github.com/docker-library/php/issues/103#issuecomment-271413933'; \
        echo 'AC_DEFUN([PHP_ALWAYS_SHARED],[])dnl'; \
        echo; \
        cat /usr/src/php/ext/odbc/config.m4; \
    } > temp.m4 \
    && mv temp.m4 /usr/src/php/ext/odbc/config.m4 \
    && docker-php-ext-install \
    	iconv \
	  	bcmath \
	  	opcache \
	  	snmp \
	  	intl \
	  	soap \
	  	xsl \
	  	bz2 \
	  	calendar \
	  	dba \
	  	enchant \
	  	exif \
	  	gettext \
	  	gmp \
	  	imap \
	  	mysqli \
	  	pcntl \
	  	pdo_mysql \
	  	pdo_pgsql \
	  	pgsql \
	  	sockets \
	  	wddx \
	  	xmlrpc \
	&& docker-php-ext-configure gd -enable-gd-native-ttf --with-freetype-dir=/usr/include/ --with-jpeg-dir=/usr/include/ \
	&& docker-php-ext-install gd \
	&& docker-php-ext-configure zip --with-libzip \
	&& docker-php-ext-install zip \
	&& docker-php-ext-configure imap --with-kerberos --with-imap-ssl \
	&& docker-php-ext-install -j$(nproc) imap \
	&& docker-php-ext-configure ldap --with-libdir=lib/ \
    && docker-php-ext-install ldap \
    && docker-php-ext-configure pdo_odbc --with-pdo-odbc=unixODBC,/usr \
	&& docker-php-ext-install pdo_odbc \
	&& docker-php-ext-configure odbc --with-unixODBC=shared,/usr \
	&& docker-php-ext-install odbc \
	&& pecl install \
		oauth \
		mcrypt-1.0.2 \
		apcu \
		memcached \
		redis \
	&& docker-php-ext-enable \
        oauth \
        mcrypt \
        apcu \
        memcached \
        redis \
    && docker-php-source delete \
    && runDeps="$( \
        scanelf --needed --nobanner --format '%n#p' --recursive /usr/local \
            | tr ',' '\n' \
            | sort -u \
            | awk 'system("[ -e /usr/local/lib/" $1 " ]") == 0 { next } { print "so:" $1 }' \
    )" \
    && apk add --no-cache --virtual .php-rundeps $runDeps \
	&& apk del .build-deps

# Install Composer

RUN set -ex \
	&& curl -sS https://getcomposer.org/installer | php -- --install-dir=/usr/local/bin/ --filename=composer

USER www-data

RUN set -ex \
	&& mkdir -p /home/www-data/.composer \
	&& composer g require \
		hirak/prestissimo \
		psy/psysh:@stable \
	&& rm -rf /home/www-data/.composer/cache/*

ENV PATH="/home/www-data/.composer/vendor/bin:${PATH}"

USER root
